name: weather_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  dartz: 0.10.1
  equatable: 2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.0
  get_it: 8.0.3
  http: 1.4.0
  injectable: 2.5.0
  injectable_generator: 2.5.0
  intl: 0.20.2
  json_annotation: 4.9.0


dev_dependencies:
  bloc_test: 10.0.0
  build_runner: 2.4.13
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  json_serializable: 6.9.0
  mockito: 5.4.4
  network_image_mock: 2.1.1

flutter:

  uses-material-design: true
