name: weather_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  dartz: 0.10.1
  equatable: 2.0.7
  flutter:
    sdk: flutter
  json_annotation: 4.9.0


dev_dependencies:
  build_runner: 2.4.13
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  json_serializable: 6.9.0

flutter:

  uses-material-design: true
